[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# azurite_errors = { path = "../azurite_errors" }
itertools = "*"
istd = { git = "https://github.com/rookieCookies/istd" }